# Generated by Django 6.0 on 2026-01-14 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='face_image',
            field=models.ImageField(blank=True, null=True, upload_to='faces/'),
        ),
    ]
